services:
  - type: web
    name: papeleria-backend
    env: node
    region: oregon
    plan: free
    autoDeploy: true
    envVars:
      - key: SUPABASE_DATABASE_URL
      - key: JWT_SECRET
      - key: SUPABASE_URL
      - key: SUPABASE_SERVICE_KEY
